Repository Metroscope-dev/metroscope-modeling-library, pull requests merged in 2023-08, with the labels that each got.

#446 🆕 Added fuel valve component
  CHANGELOG.md
  MetroscopeModelingLibrary/Fuel/Pipes/ControlValve.mo
  MetroscopeModelingLibrary/Tests/Fuel/Pipes/ControlValve_direct.mo
  MetroscopeModelingLibrary/Tests/Fuel/Pipes/ControlValve_reverse.mo
  MetroscopeModelingLibrary/Tests/Fuel/Pipes/package.order
Labels: ✨enhancement, :new: New component

#450 Pressure loss simplification
  CHANGELOG.md
  MetroscopeModelingLibrary/Examples/Nuclear/MetroscopiaNPP/MetroscopiaNPP_direct.mo
  MetroscopeModelingLibrary/Examples/Nuclear/MetroscopiaNPP/MetroscopiaNPP_reverse.mo
  MetroscopeModelingLibrary/FlueGases/BaseClasses/FlowModel.mo
  MetroscopeModelingLibrary/FlueGases/BaseClasses/IsoHFlowModel.mo
  MetroscopeModelingLibrary/FlueGases/BaseClasses/IsoPFlowModel.mo
  MetroscopeModelingLibrary/FlueGases/BaseClasses/IsoPHFlowModel.mo
  MetroscopeModelingLibrary/FlueGases/Machines/AirCompressor.mo
  MetroscopeModelingLibrary/FlueGases/Machines/GasTurbine.mo
  MetroscopeModelingLibrary/FlueGases/Pipes/ControlValve.mo
  MetroscopeModelingLibrary/FlueGases/Pipes/HeatLoss.mo
  MetroscopeModelingLibrary/FlueGases/Pipes/Pipe.mo
  MetroscopeModelingLibrary/Partial/Pipes/ControlValve.mo
  MetroscopeModelingLibrary/Partial/Pipes/Pipe.mo
  MetroscopeModelingLibrary/Partial/Pipes/SlideValve.mo
Labels: ✨enhancement

#448 Reset v3.6.1
  CHANGELOG.md
Labels: 🔖release
