Repository Metroscope-dev/metroscope-modeling-library, pull requests merged in 2023-07, with the labels that each got.

#435 :bookmark: Bump v3.6.1
  CHANGELOG.md
  MetroscopeModelingLibrary/package.mo
Labels: 🔖release

#439 Initialisation values corrections
  CHANGELOG.md
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/MetroscopiaCCGT_direct.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Evaporator.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Superheater.mo
  MetroscopeModelingLibrary/Partial/HeatExchangers/WaterFlueGasesMonophasicHX.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/Economiser_direct.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/Economiser_reverse.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/Evaporator_direct.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/Evaporator_reverse.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/Superheater_direct.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/Superheater_reverse.mo
Labels: 🐛bug

#440 Adjustments of initialization values
  CHANGELOG.md
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/MetroscopiaCCGT_direct.mo
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/MetroscopiaCCGT_faulty.mo
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/package.order
  MetroscopeModelingLibrary/Partial/BaseClasses/FlowModel.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Condenser.mo
Labels: 🐛bug

#442 HX indicators
  CHANGELOG.md
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/MetroscopiaCCGT_reverse.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Evaporator.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/FuelHeater.mo
  MetroscopeModelingLibrary/Partial/HeatExchangers/WaterFlueGasesMonophasicHX.mo
  MetroscopeModelingLibrary/Power/HeatExchange/NTUHeatExchange.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/FuelHeater_direct.mo
  MetroscopeModelingLibrary/Tests/Multifluid/HeatExchangers/FuelHeater_reverse.mo
  MetroscopeModelingLibrary/Tests/WaterSteam/HeatExchangers/Reheater_reverse.mo
  MetroscopeModelingLibrary/Tests/WaterSteam/HeatExchangers/Superheater_reverse.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Condenser.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/DryReheater.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/LiqLiqHX.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reheater.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Superheater.mo
Labels: ✨enhancement

#443 Added standard performance indicators for HX
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Economiser.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Evaporator.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/FuelHeater.mo
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Superheater.mo
  MetroscopeModelingLibrary/Partial/HeatExchangers/WaterFlueGasesMonophasicHX.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/DryReheater.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/LiqLiqHX.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reheater.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Superheater.mo
Labels: ✨enhancement

#445 Warning if steam is superheated at the condenser inlet
  CHANGELOG.md
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/Superheater.mo
  MetroscopeModelingLibrary/Tests/WaterSteam/HeatExchangers/Condenser_direct.mo
  MetroscopeModelingLibrary/Tests/WaterSteam/HeatExchangers/Condenser_reverse.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Condenser.mo
Labels: ✨enhancement
