Repository Metroscope-dev/metroscope-modeling-library, pull requests merged in 2024-10, with the labels that each got.

#499 Unprotect states in HX and updated units, propagated start values parameters in sources
  CHANGELOG.md
  MetroscopeModelingLibrary/FlueGases/Pipes/LoopBreaker.mo
  MetroscopeModelingLibrary/FlueGases/Pipes/package.order
  MetroscopeModelingLibrary/MultiFluid/HeatExchangers/FuelHeater.mo
  MetroscopeModelingLibrary/MultiFluid/Machines/CombustionChamber.mo
  MetroscopeModelingLibrary/Partial/BoundaryConditions/FluidSource.mo
  MetroscopeModelingLibrary/Partial/HeatExchangers/WaterFlueGasesMonophasicHX.mo
  MetroscopeModelingLibrary/Partial/Machines/Pump.mo
  MetroscopeModelingLibrary/Partial/Sensors/BaseSensor.mo
  MetroscopeModelingLibrary/Sensors/MoistAir/PressureSensor.mo
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Reactor.mo
Labels: :beginner: Start values

#502 Relative Humidity Sensor
  CHANGELOG.md
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/MetroscopiaCCGT_direct.mo
  MetroscopeModelingLibrary/Examples/CCGT/MetroscopiaCCGT/MetroscopiaCCGT_reverse.mo
  MetroscopeModelingLibrary/Sensors/MoistAir/RelativeHumiditySensor.mo
  MetroscopeModelingLibrary/Sensors/MoistAir/package.order
  MetroscopeModelingLibrary/Tests/Sensors/MoistAir/RelativeHumiditySensor.mo
  MetroscopeModelingLibrary/Tests/Sensors/MoistAir/package.order
  MetroscopeModelingLibrary/Tests/package.mo
Labels: ✨enhancement

#508 Added Filter and Control Valve blocks for RefMoistAir medium
  CHANGELOG.md
  MetroscopeModelingLibrary/RefMoistAir/Pipes/ControlValve.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/Filter.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/package.order
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/ControlValve_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/ControlValve_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Filter_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Filter_faulty.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Filter_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/package.order
Labels: ✨enhancement

#495 🔥 Remove superheaters fouling
  CHANGELOG.md
  MetroscopeModelingLibrary/WaterSteam/HeatExchangers/Superheater.mo
Labels: :hammer_and_wrench: Faults

#509 Pb combustion chamber ref moist air
  CHANGELOG.md
  MetroscopeModelingLibrary/MultiFluid/Machines/CombustionChamberWithRefMoistAir.mo
  MetroscopeModelingLibrary/MultiFluid/Machines/package.order
  MetroscopeModelingLibrary/Tests/Multifluid/Machines/CombustionChamberwithRefMoistAir.mo
  MetroscopeModelingLibrary/Tests/Multifluid/Machines/package.order
Labels: ✨enhancement

#510 Changed RefMoistAir medium color
  MetroscopeModelingLibrary/Examples/CCGT/airCompressor_with_fogging_direct.mo
  MetroscopeModelingLibrary/RefMoistAir/BaseClasses/package.mo
  MetroscopeModelingLibrary/RefMoistAir/BoundaryConditions/Sink.mo
  MetroscopeModelingLibrary/RefMoistAir/BoundaryConditions/Source.mo
  MetroscopeModelingLibrary/RefMoistAir/BoundaryConditions/package.mo
  MetroscopeModelingLibrary/RefMoistAir/Connectors/Inlet.mo
  MetroscopeModelingLibrary/RefMoistAir/Connectors/Outlet.mo
  MetroscopeModelingLibrary/RefMoistAir/Connectors/package.mo
  MetroscopeModelingLibrary/RefMoistAir/Machines/AirCompressor.mo
  MetroscopeModelingLibrary/RefMoistAir/Machines/InletGuideVanes.mo
  MetroscopeModelingLibrary/RefMoistAir/Machines/package.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/AdmiLouver.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/ControlValve.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/Filter.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/HeatLoss.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/Leak.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/Pipe.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/PressureCut.mo
  MetroscopeModelingLibrary/RefMoistAir/Pipes/package.mo
  MetroscopeModelingLibrary/RefMoistAir/package.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/BaseClasses/FlowModel.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/BaseClasses/IsoHFlowModel.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/BaseClasses/IsoPFlowModel.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/BaseClasses/IsoPHFlowModel.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/BoundaryConditions/Sink.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/BoundaryConditions/Source.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Machines/AirCompressor_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Machines/AirCompressor_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/AdmiLouvers_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/AdmiLouvers_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/ControlValve_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/ControlValve_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Filter_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Filter_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/HeatLoss.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Leak.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Pipe_direct.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/Pipe_reverse.mo
  MetroscopeModelingLibrary/Tests/RefMoistAir/Pipes/PressureCut.mo
  MetroscopeModelingLibrary/Utilities/Icons/BaseClasses/RefMoistAirBaseClassIcon.mo
  MetroscopeModelingLibrary/Utilities/Icons/Sensors/RefMoistAirSensorIcon.mo
  MetroscopeModelingLibrary/Utilities/Icons/Tests/RefMoistAirTestIcon.mo
  MetroscopeModelingLibrary/Utilities/Icons/Tests/RefMoistAirTestPackageIcon/package.mo
  MetroscopeModelingLibrary/Utilities/Media/RefMoistAirMedium/package.mo
Labels: 💄style
